---
- name: Install Grafana on EC2 instance
  hosts: grafana_server
  become: yes

  vars:
    grafana_version: "10.4.1"
    grafana_rpm: "grafana-{{ grafana_version }}-1.x86_64.rpm"
    grafana_url: "https://dl.grafana.com/oss/release/{{ grafana_rpm }}"

  tasks:

    - name: Install dependencies
      yum:
        name: fontconfig
        state: present

    - name: Download Grafana RPM
      get_url:
        url: "{{ grafana_url }}"
        dest: "/tmp/{{ grafana_rpm }}"

    - name: Install Grafana RPM package
      yum:
        name: "/tmp/{{ grafana_rpm }}"
        state: present

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Ensure Grafana is running
      uri:
        url: http://localhost:3000
        status_code: 200
        return_content: no
        validate_certs: no
      register: grafana_status
      failed_when: grafana_status.status != 200
      retries: 5
      delay: 5
      until: grafana_status.status == 200
